### ISSUE TITLE
Discrepancy between ruler pointer and displayed value

### ISSUE THREAD

**Issue by ziselos** [AbdElraoufSabri/FancyAndroidRuler#11]
There is a discrepancy between the pointer and the actual value. For example the pointer is on position 69 on ruler and the text displays 70 as value. Or on the demo code, the pointer is on position 275 but the displayed value is like we are at the end on position 280

**Comment by abd3lraouf** [comment]
I can't reproduce the issue but will dig deeper.

**Comment by abd3lraouf** [comment]
@ziselos Please check the latest version fixed your issue or not? 
Please note that I migrated the project under a new group and artifact, the Gradle dependency now is

`dev.abd3lraouf.ruler:android:1.6.1`

**Comment by ziselos** [comment]
Thanks for the reply. Yes it seems fine now. On real device it is ok. The problem probably is on emulator behavior. When you scroll rapidly to the end for example pointer is on different position than the displayed value. On real device it is correct.
